import type { Metadata } from 'next'
import { Inter, Mulish } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer'
import { AuthProvider } from '@/providers/auth'

const inter = Inter({ subsets: ['latin'] })

const mulish = Mulish({subsets: ['latin'], weight: ['400', '500', '600', '700', '800']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${mulish.className} dark`}>
        <AuthProvider>
          {children}
          <Footer/>
        </AuthProvider>
      </body>
    </html>
  )
}
